# Example values for development/testing with Personal Access Token (PAT)
# 
# WARNING: PAT authentication is NOT recommended for production use
# For production, use OAuth + External Token Provider (see values-oauth-production.yaml)
# See AUTHENTICATION.md for production authentication setup

# Dremio configuration with PAT
dremio:
  # Dremio Software instance URI
  uri: "https://dremio.example.com:9047"

  # Personal Access Token for authentication
  # NOT RECOMMENDED FOR PRODUCTION - use OAuth instead
  pat: "your-personal-access-token-here"

  # Alternatively, use an existing Kubernetes secret
  # The secret should have a key named 'pat'
  # existingSecret: "my-dremio-secret"

  # Allow DML operations
  allowDml: false

# MCP Server configuration
mcp:
  enableStreamingHttp: true
  port: 8000
  host: "0.0.0.0"
  
  logging:
    enableJson: false
    level: "DEBUG"
    toFile: false

# Tools configuration
tools:
  serverMode: "FOR_DATA_PATTERNS"

# Metrics configuration
metrics:
  enabled: false

# Image configuration
image:
  repository: dremio-mcp
  pullPolicy: IfNotPresent
  tag: "0.1.0"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Service configuration
service:
  type: ClusterIP
  port: 8000

# Ingress disabled for dev/test
ingress:
  enabled: false

# Single replica for dev/test
replicaCount: 1

# Autoscaling disabled
autoscaling:
  enabled: false

