# Example values using an existing Kubernetes secret for PAT
# 
# This approach is useful when:
# - You manage secrets separately (e.g., with external-secrets, sealed-secrets, Vault)
# - You want to avoid storing PAT in values files
# - You're using GitOps and want to keep secrets out of Git
#
# Prerequisites:
# 1. Create a secret with your PAT:
#    kubectl create secret generic my-dremio-secret \
#      --from-literal=pat=your-personal-access-token \
#      -n dremio
#
# WARNING: PAT authentication is NOT recommended for production
# For production, use OAuth + External Token Provider (see values-oauth-production.yaml)

# Dremio configuration with existing secret
dremio:
  # Dremio Software instance URI
  uri: "https://dremio.example.com:9047"

  # Reference to existing Kubernetes secret containing PAT
  # The secret must have a key named 'pat'
  existingSecret: "my-dremio-secret"

  # Do NOT set dremio.pat when using existingSecret
  # pat: ""

  # Allow DML operations
  allowDml: false

# MCP Server configuration
mcp:
  enableStreamingHttp: true
  port: 8000
  host: "0.0.0.0"
  
  logging:
    enableJson: false
    level: "INFO"
    toFile: false

# Tools configuration
tools:
  serverMode: "FOR_SELF,FOR_DATA_PATTERNS"

# Metrics configuration
metrics:
  enabled: true
  port: 9091

# Image configuration
image:
  repository: dremio-mcp
  pullPolicy: IfNotPresent
  tag: "0.1.0"

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  port: 8000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"

# Ingress configuration
ingress:
  enabled: false

# Replica count
replicaCount: 2

# Autoscaling
autoscaling:
  enabled: false

